# Aliases
setopt aliases
alias l='ls -F --color=auto'
alias ls='ls -F --color=auto'
alias ll='ls -lF --color=auto'
alias la='ls -aF --color=auto'
alias lla='ls -laF --color=auto'
alias x='exit'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias dirs='dirs -v'
alias pd='popd'
alias b='cd ../'
alias e='emacs'
alias sless='less -S'
alias lasth='last | head'
alias grep='grep --color=auto'
alias ta='tmux attach'
alias tn='tmux new'
alias today='date +%Y%m%d'
alias nkf2utf8='nkf -w'
alias jless='jq . -C | less -R'
alias tree='tree -N'
alias i='ipython'
alias c='code .'
alias hb='hub browse'
alias p='poetry'
alias pr='poetry run'
alias pri='poetry run ipython'
alias prodigy="python -m prodigy"
alias t='tmux attach || tmux new'
alias sed='gsed'
alias cc="claude"
alias yolo="claude --dangerously-skip-permissions"
alias gl='git com && git pl'
